answers:
  start_without_group: "Привет &#128075; Напиши название учебной группы, чтобы узнать её расписание. Например, МПГДбд-11 или ИСдо-11."
  start_with_group: "Привет &#128075; Напиши:\n\n&#128313; «1» или «Моё расписание», чтобы перейти к расписанию выбранной группы\n\n&#128313; «2» или «Изменить группу», чтобы поменять группу, расписание которой ты будешь получать"
  change_group: "Напиши название учебной группы &#9999; Например, МПГДбд-11 или ИСдо-11."
  back: "Напиши:\n\n&#128313; «1» или «Моё расписание», чтобы перейти к расписанию выбранной группы\n\n&#128313; «2» или «Изменить группу», чтобы поменять группу, расписание которой ты будешь получать"
  info_without_group: "Напиши название учебной группы, чтобы узнать её расписание &#9999; Например, МПГДбд-11 или ИСдо-11."
  info_with_group: "Напиши:\n\n&#128313; «3» или «Сегодня», чтобы получить расписание на сегодняшний день\n\n&#128313; «4» или «Завтра», чтобы узнать расписание на завтрашний день\n\n&#128313; «5» или «Текущая неделя», чтобы узнать расписание на текущую неделю\n\n&#128313; «6» или «Следующая неделя», чтобы узнать расписание на следующую неделю\n\n&#128313; «7» или «Назад», чтобы вернуться в главное меню"
  thanks: "Хочешь поддержать наш проект? Жми на кнопку ниже &#128071;"

additions:
  thanks_not_subscribed: "Надеемся, что подписочка на нас уже оформлена &#128521;"
  info_not_subscribed: "Подпишись на [scheduleofulstu|нашу группу] – тебе откроются команды «Текущая неделя» и «Следующая неделя», и недельное расписание всегда будет при тебе (а это сообщение вовсе перестанет приходить!) &#128521;"
  changes_in_kei_schedule: "Возможные изменения в расписании: https://vk.cc/bWfVyE"

errors:
  incorrect_input: "Возможно, название команды или группы написано неверно. Проверь правильность написания и повтори попытку &#128257;"
  group_not_selected: "Группа не выбрана! Напиши название группы, чтобы узнать её расписание &#9999; Например, МПГДбд-11 или ПИбд-21 (Название группы такое же, как и на сайте с расписанием)."
  student_not_subscribed: "Эта команда доступна только подписчикам! Подписывайся на [scheduleofulstu|нашу группу] и получай расписание на текущую и следующую недели &#128527;"
  curr_week_schedule_is_unavailable: "К сожалению, расписание на текущую неделю временно недоступно... Повтори попытку позже &#128257;"
  next_week_schedule_is_unavailable: "К сожалению, расписание на следующую неделю временно недоступно... Повтори попытку позже &#128257;"
  failed_to_update_group: "К сожалению, не удалось обновить учебную группу... Повтори попытку позже &#128257;"
  server_error: "К сожалению, произошла ошибка при обращении к серверу... Повтори попытку позже &#128257;"
  database_error: "К сожалению, произошла ошибка при обращении к базе данных... Повтори попытку позже &#128257;"
  week_schedule_uploading_error: "К сожалению, произошла непредвиденная ошибка при генерации расписания... Повтори попытку позже &#128257;"

sticker_ids:
  to_sticker:
    - 20050
    - 20027
    - 20043
    - 20058
    - 15211
    - 15229
  to_audio_message:
    - 20052
    - 17687